# Generated by Django 4.0.6 on 2022-08-24 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_in', models.DateField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('record_type', models.BooleanField()),
                ('date_in', models.DateField(auto_now_add=True)),
                ('id_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo_cash.balance')),
                ('id_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluxo_cash.tag')),
            ],
        ),
    ]
