# Generated by Django 4.0.6 on 2022-08-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('date_in',)},
        ),
    ]
