# Generated by Django 4.0.6 on 2022-08-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_cash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='id_user',
            new_name='id_userProfile',
        ),
        migrations.AlterField(
            model_name='record',
            name='date_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
