# Generated by Django 4.0.6 on 2022-08-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_cash', '0002_rename_id_user_record_id_userprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Record_type',
            new_name='record_type',
        ),
    ]
